### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by JLineaweaver** [JayTeeGeezy/predictivepunter#18]
Hey sorry this isn't an issue.  I've been looking into statistics and horse racing, and I came across your repo.  I haven't built it yet, but I wanted to know if you were still working on it?  Would love to have some experienced in this to speak to.   Also I wouldn't mind contributing.

**Comment by razche1** [comment]
Did you ever get around to building this JLineaweaver?

**Comment by JLineaweaver** [comment]
No I never did.  Ended up working on other sports
